name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3.0.2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2.0.0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.0.0
      -
        name: base
        run: make base
      -
        name: unit-tests
        run: make unit-tests
      -
        name: codecov
        uses: codecov/codecov-action@v3.1.1
        with:
          files: ./_out/coverage.txt
      -
        name: unit-tests-race
        run: make unit-tests-race
      -
        name: lint
        run: make lint
